geometry_msgs/Vector3 position
float32 yaw
float32 altitude
bool altitude_mode

# If blocking never finalizes
bool blocking
uint8 priority

uint8 REFERENCE_NED=0
uint8 REFERENCE_GLOBAL=1
uint8 REFERENCE_VEHICLE=2
uint8 reference

# GOTO:             False,  True,   ?,      True,   True,   False
# HOLONOMIC GOTO:   False,  False,  ?,      True,   True,   ?
# SUBMERGE:         True,   True,   False,  True,   True,   True
auv_msgs/Bool6Axis disable_axis

geometry_msgs/Vector3 position_tolerance
auv_msgs/RPY orientation_tolerance
---
bool success
